version: "3"
services:
  dssv-dev-env:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        - username=dev
        - userid=1000
    container_name: dssv
    image: dssv
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ../:/home/dev/data-science-sv
    command: jupyter notebook --ip='0.0.0.0' --port=8888 --no-browser
